const S = {
  page: {
    minHeight: "100vh",
    background: "#000",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "system-ui, -apple-system, sans-serif",
    padding: "24px 16px",
  },
  card: {
    width: "100%",
    maxWidth: 440,
    background: "#111111",
    padding: "36px 32px",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.1)",
    boxShadow: "0 24px 80px rgba(0,0,0,0.6)",
  },
  brand: {
    color: "#FFC107",
    margin: 0,
    fontSize: 32,
    fontWeight: 900,
    letterSpacing: "-1px",
  },
  sub: {
    color: "#71717A",
    fontSize: 14,
    marginTop: 6,
    marginBottom: 0,
  },
  toggle: {
    display: "flex",
    gap: 6,
    marginBottom: 20,
    background: "#0A0A0A",
    borderRadius: 12,
    padding: 4,
    border: "1px solid rgba(255,255,255,0.07)",
  },
  toggleBtn: {
    flex: 1,
    padding: "10px 0",
    background: "transparent",
    color: "#71717A",
    border: "none",
    borderRadius: 9,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  toggleActive: {
    background: "#FFC107",
    color: "#000",
    boxShadow: "0 2px 8px rgba(255,193,7,0.3)",
  },
  errorBox: {
    background: "rgba(239,68,68,0.1)",
    border: "1px solid rgba(239,68,68,0.35)",
    color: "#EF4444",
    borderRadius: 10,
    padding: "10px 14px",
    marginBottom: 12,
    fontSize: 13.5,
    lineHeight: 1.5,
  },
  label: {
    display: "block",
    color: "#A1A1AA",
    fontSize: 12,
    fontWeight: 600,
    marginBottom: 6,
    letterSpacing: "0.3px",
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    padding: "13px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "#1A1A1A",
    color: "white",
    boxSizing: "border-box",
    fontFamily: "inherit",
    fontSize: 15,
    outline: "none",
    transition: "border-color 0.15s",
  },
  eyeBtn: {
    position: "absolute",
    right: 12,
    top: "50%",
    transform: "translateY(-50%)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: 16,
    lineHeight: 1,
    padding: 2,
  },
  btn: {
    width: "100%",
    padding: "14px 0",
    background: "linear-gradient(135deg, #FFC107 0%, #E6AC00 100%)",
    color: "#000",
    border: "none",
    borderRadius: 11,
    fontWeight: 800,
    fontSize: 15,
    fontFamily: "inherit",
    letterSpacing: "0.2px",
    boxShadow: "0 4px 20px rgba(255,193,7,0.25)",
    transition: "transform 0.1s, box-shadow 0.1s",
  },
  switchHint: {
    textAlign: "center",
    color: "#71717A",
    fontSize: 13.5,
    marginTop: 18,
    marginBottom: 0,
  },
  switchLink: {
    background: "transparent",
    border: "none",
    color: "#FFC107",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "inherit",
    fontFamily: "inherit",
    padding: 0,
    textDecoration: "underline",
    textUnderlineOffset: 2,
  },
};

export default S;